### ISSUE TITLE
There's a similar crate error-stack

### ISSUE THREAD

**Issue by QAston** [AaronKutch/stacked_errors#7]
Hi,

Feel free to close this issue if not relevant. I just wanted to let you know that there's a similar crate already called [error-stack](https://github.com/hashintel/hash/tree/main/libs/error-stack). You might want to combine the efforts as the approaches seem pretty close (name similarity isn't an accident).

**Comment by AaronKutch** [comment]
That's strange, I remember when making `stacked_errors` that I made it because I could not find another error crate that could satisfy my needs. The primary issue I needed to fix, was that when the async callstacks would get impressively deep and with many alternative callers (e.x. when using my https://crates.io/crates/super_orchestrator crate), it would be impossible to know where exactly errors were being propogated up from. I notice that `error-stack` it isn't in a standalone repository for some reason, I'm guessing it was started for the same reasons when working on Hash, and it remained in the monorepo. Funny that they ended up with a macro named `ensure` like I did, or did I get that inspiration from another crate? Are you associated with them?

The second thing is that `map_err` is incredibly cumbersome and _ridiculously_ cumbersome in large test functions where every other line has fallible points, in most cases I can just call `.stack()?` when I need it and everything from the conversion to the location addition is handled automatically. I should note that my `stacked_errors` is not intended to be used at low levels (except if you are starting with OS level commands like in file operations or what databases typically do), mid to lower level crates should use their own error enums. Again, it is intended for where domains collide or complicated `async/await` is at play.

Looking briefly over `error-stack`, it appears to use `Backtrace`s instead of my `Location` based approach. Does this actually work in `async` environments, because last time I checked OS backtraces were practically useless in `async` because they just point at `tokio` handlers or whatever. My crate essentially rolls its own backtrace functionality and makes it relatively cheap by using `thin-vec` and pushing `&'static Location`s and `&'static str` in common cases, [whatever `error-stack` is doing](https://docs.rs/error-stack/0.4.1/src/error_stack/report.rs.html#400) is definitely more expensive and verbose. It does appear to have more refined features and better display output though.

**Comment by AaronKutch** [comment]
I'm seeing an awful lot of `unwrap` in their own examples, I'm pretty sure they don't have the same focuses as I do. Take for example https://github.com/onomyprotocol/manual_tests/blob/main/tests/src/bin/query_graph.rs . Every point with `stack` is another point where I don't have to deal with println debugging when trying to find the callstack. Of course this example is at the top level and most points have a uniquely determinable callstack, but even then it saves me time from chasing function calls when finding the middle of the callstack.

**Comment by QAston** [comment]
I'm looking for a library that would work with actix/tokio, so I'll take a look, if your library works better than that one I'll use it instead, thanks!
